package hwr.oop.examples.template.core

class Tile (val color: TileColor, val number: TileNumber) {
	
	fun color(): TileColor {
		return this.color
	}
	
	fun number(): TileNumber {
		return this.number
	}
	
	// The following are intellij autogenerated
	
	override fun toString(): String {
		return "Tile(color=$color, number=$number)"
	}
	
	override fun equals(other: Any?): Boolean {
		if (this === other) return true
		if (javaClass != other?.javaClass) return false
		
		other as Tile
		
		if (color != other.color) return false
		if (number != other.number) return false
		
		return true
	}
}